### ISSUE TITLE
Resizing form

### ISSUE THREAD

**Issue by EthemAcar-Dev** [xv/XRails-LoginUI#1]
What about a workaround? Sure -- although not entirely. Form resizing during runtime can be easily coded and implemented in XRails_Container.

I couldn't manage to do this, my little knowledge in WinForms failed me at this task. Could you help?

**Comment by xv** [comment]
Hi, sorry for the late reply. Life's been keeping me busy.

The easiest way to achieve resizing is probably by hit-testing mouse coordinates to determine which corner corresponds to which coordinate.

This project is in a finished state and I don't feel like modifying at this point. However, I created a new project at [/xv/winforms-true-borderless](https://github.com/xv/winforms-true-borderless) not that long ago that demonstrates borderless form creation with optional resizing, DWM animations, etc. It's still in WIP state but everything is implemented for the most part. You can check it out and see how it works.
